# Generated by Django 6.0.5 on 2026-06-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('botanical_name', models.CharField(max_length=160)),
                ('family', models.CharField(max_length=120)),
                ('uses', models.JSONField(default=list)),
                ('parts_used', models.JSONField(default=list)),
                ('preparation', models.TextField()),
                ('caution', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
